title: My Blog
description: Just for fun
author: xoeg

remote_theme: jekyll/minima@v2.5.2

minima:
  show_excerpts: true
  social_links:
    - title: GitHub
      icon: github
      url: "https://github.com/xoeg"

markdown: kramdown
kramdown:
  math_engine: null

plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
