title: My Blog
description: My blog
author: xoeg
theme: minima

# Social links
minima:
  social_links:
    github: xoeg

# MathJax (LaTeX math support)
markdown: kramdown
kramdown:
  math_engine: mathjax

head_scripts:
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
